package ua.pp.hak.util;

import java.util.HashMap;
import java.util.Map;

public class Legacy {
	private static HashMap<String, String> legacy;

	public static HashMap<String, String> getLegacy() {
		return legacy;
	}

	static {
		initLegacy();
	}

	public static String getLecagyName(String legacyCode) {
		return legacy.get(legacyCode);
	}

	public static String getLecagyCode(String legacyName) {
		for (Map.Entry<String, String> entry : legacy.entrySet()) {
			if (entry.getValue().equals(legacyName)){
				return entry.getKey();
			}
		}
		return null;
	}

	private static void initLegacy() {
		// \u2022 - aka dot. is used due to UFT-8
		legacy = new HashMap<>();
		legacy.put("0", "Office Supplies");
		legacy.put("0A", "Office Supplies \u2022 Books & Pads");
		legacy.put("0B", "Office Supplies \u2022 Forms");
		legacy.put("0C", "Office Supplies \u2022 Writing & Drawing Tools");
		legacy.put("0D", "Office Supplies \u2022 Craft & Art Supplies");
		legacy.put("0E", "Office Supplies \u2022 Filing & Storage");
		legacy.put("0F", "Office Supplies \u2022 Presentation");
		legacy.put("0G", "Office Supplies \u2022 Presentation Accessories");
		legacy.put("0H", "Office Supplies \u2022 Clips, Pins & Staples");
		legacy.put("0I", "Office Supplies \u2022 Stamps & Accessories");
		legacy.put("0J", "Office Supplies \u2022 Desk Accessories");
		legacy.put("1", "Shipping & Packaging");
		legacy.put("1A", "Shipping & Packaging \u2022 Envelopes & Shipping Boxes");
		legacy.put("1B", "Shipping & Packaging \u2022 Tape & Dispensers");
		legacy.put("1C", "Shipping & Packaging \u2022 Packaging Materials");
		legacy.put("1D", "Shipping & Packaging \u2022 Mailroom & Packaging Equipment");
		legacy.put("2", "Janitorial & Facilities");
		legacy.put("2A", "Janitorial & Facilities \u2022 Trash Bags & Cans");
		legacy.put("2B", "Janitorial & Facilities \u2022 Cleaning Tools");
		legacy.put("2C", "Janitorial & Facilities \u2022 Household Chemicals");
		legacy.put("2D", "Janitorial & Facilities \u2022 Hygiene");
		legacy.put("2E", "Janitorial & Facilities \u2022 Lighting");
		legacy.put("2I", "Janitorial & Facilities \u2022 Workwear & Safety");
		legacy.put("2J", "Janitorial & Facilities \u2022 Signage & Posters");
		legacy.put("3", "Food & Beverages");
		legacy.put("3A", "Food & Beverages \u2022 Food");
		legacy.put("3B", "Food & Beverages \u2022 Beverages");
		legacy.put("3Z", "Food & Beverages \u2022 Quantity Units of Measure");
		legacy.put("4", "Furniture");
		legacy.put("4A", "Furniture \u2022 Surfaces");
		legacy.put("4B", "Furniture \u2022 Seating");
		legacy.put("4C", "Furniture \u2022 Storage Furniture");
		legacy.put("4D", "Furniture \u2022 Decoration");
		legacy.put("4K", "Furniture \u2022 Furniture Accessories");
		legacy.put("5", "Construction & Repair");
		legacy.put("5A", "Construction & Repair \u2022 Hand Tools");
		legacy.put("5B", "Construction & Repair \u2022 Power Tools");
		legacy.put("5C", "Construction & Repair \u2022 Construction Equipment");
		legacy.put("5D", "Construction & Repair \u2022 Locking Systems");
		legacy.put("5E", "Construction & Repair \u2022 Integrated Systems & Automation");
		legacy.put("5F", "Construction & Repair \u2022 Outdoor Power Tools");
		legacy.put("5G", "Construction & Repair \u2022 Power Tool Accessories");
		legacy.put("6", "Toys, Kids & Baby");
		legacy.put("6A", "Toys, Kids & Baby \u2022 Toys");
		legacy.put("6B", "Toys, Kids & Baby \u2022 Blocks & Building Sets");
		legacy.put("6C", "Toys, Kids & Baby \u2022 Games & Puzzles");
		legacy.put("6D", "Toys, Kids & Baby \u2022 Outdoor Play");
		legacy.put("7", "Sports & Recreation");
		legacy.put("7A", "Sports & Recreation \u2022 Exercise & Fitness Equipment");
		legacy.put("7B", "Sports & Recreation \u2022 Field, Court & Rink Equipment");
		legacy.put("7C", "Sports & Recreation \u2022 Cycling");
		legacy.put("7D", "Sports & Recreation \u2022 Scooters, Skateboards & Skates");
		legacy.put("7E", "Sports & Recreation \u2022 Leisure Sports & Game Room");
		legacy.put("9", "Clothing, Shoes & Jewelry");
		legacy.put("9C", "Clothing, Shoes & Jewelry \u2022 Watches");
		legacy.put("A", "Systems");
		legacy.put("AA", "Systems \u2022 Desktops & Servers");
		legacy.put("AB", "Systems \u2022 Notebooks");
		legacy.put("AC", "Systems \u2022 Tablets & e-Book Readers");
		legacy.put("AD", "Systems \u2022 Processor Upgrades");
		legacy.put("AE", "Systems \u2022 Motherboards");
		legacy.put("AF", "Systems \u2022 System Cabinets");
		legacy.put("AG", "Systems \u2022 UPS & Power Devices");
		legacy.put("AH", "Systems \u2022 System & Power Cables");
		legacy.put("AI", "Systems \u2022 Port Expansion");
		legacy.put("AJ", "Systems \u2022 System Accessories");
		legacy.put("AK", "Systems \u2022 System Service & Support");
		legacy.put("B", "Memory");
		legacy.put("BA", "Memory \u2022 RAM");
		legacy.put("BB", "Memory \u2022 Video Memory");
		legacy.put("BC", "Memory \u2022 Cache Memory");
		legacy.put("BD", "Memory \u2022 Flash Memory");
		legacy.put("BE", "Memory \u2022 Read-Only Memory");
		legacy.put("BF", "Memory \u2022 Memory Adapters");
		legacy.put("C", "Storage Devices");
		legacy.put("CA", "Storage Devices \u2022 Hard Drives");
		legacy.put("CB", "Storage Devices \u2022 Undefined");
		legacy.put("CC", "Storage Devices \u2022 Disk Drives");
		legacy.put("CD", "Storage Devices \u2022 Tape Drives");
		legacy.put("CE", "Storage Devices \u2022 Network Storage");
		legacy.put("CF", "Storage Devices \u2022 Removable Media");
		legacy.put("CG", "Storage Devices \u2022 Storage Adapters");
		legacy.put("CH", "Storage Devices \u2022 Storage Cables");
		legacy.put("CI", "Storage Devices \u2022 Storage Enclosures & RAID Arrays");
		legacy.put("CJ", "Storage Devices \u2022 Storage Accessories");
		legacy.put("CK", "Storage Devices \u2022 Storage Service & Support");
		legacy.put("D", "Input Devices");
		legacy.put("DA", "Input Devices \u2022 Keyboards");
		legacy.put("DB", "Input Devices \u2022 Pointing Devices");
		legacy.put("DC", "Input Devices \u2022 Game Controllers");
		legacy.put("DD", "Input Devices \u2022 Scanners");
		legacy.put("DE", "Input Devices \u2022 Bar Code Readers");
		legacy.put("DF", "Input Devices \u2022 Audio Input");
		legacy.put("DG", "Input Devices \u2022 PC & Network Cameras");
		legacy.put("DH", "Input Devices \u2022 Input Adapters");
		legacy.put("DI", "Input Devices \u2022 Input Cables");
		legacy.put("DJ", "Input Devices \u2022 Input Accessories");
		legacy.put("DK", "Input Devices \u2022 Input Service & Support");
		legacy.put("E", "Output Devices");
		legacy.put("EA", "Output Devices \u2022 Monitors");
		legacy.put("EB", "Output Devices \u2022 Presentation Monitors");
		legacy.put("EC", "Output Devices \u2022 Projectors");
		legacy.put("ED", "Output Devices \u2022 Printers");
		legacy.put("EE", "Output Devices \u2022 Audio Output");
		legacy.put("EF", "Output Devices \u2022 Video Cards");
		legacy.put("EG", "Output Devices \u2022 Sound Cards");
		legacy.put("EH", "Output Devices \u2022 Output Cables");
		legacy.put("EI", "Output Devices \u2022 Printer Consumables");
		legacy.put("EJ", "Output Devices \u2022 Output Accessories");
		legacy.put("EK", "Output Devices \u2022 Output Service & Support");
		legacy.put("F", "Networking");
		legacy.put("FA", "Networking \u2022 Modems");
		legacy.put("FB", "Networking \u2022 Video Conferencing");
		legacy.put("FC", "Networking \u2022 Concentrators & Multiplexers");
		legacy.put("FD", "Networking \u2022 Repeaters & Transceivers");
		legacy.put("FE", "Networking \u2022 Hubs & Switches");
		legacy.put("FF", "Networking \u2022 Bridges & Routers");
		legacy.put("FG", "Networking \u2022 Network Devices");
		legacy.put("FH", "Networking \u2022 Network Adapters");
		legacy.put("FI", "Networking \u2022 Network Cables");
		legacy.put("FJ", "Networking \u2022 Network Accessories");
		legacy.put("FK", "Networking \u2022 Network Service & Support");
		legacy.put("FL", "Networking \u2022 Network Testers");
		legacy.put("FM", "Networking \u2022 Business Phone Systems");
		legacy.put("G", "Software");
		legacy.put("GA", "Software \u2022 Operating Systems");
		legacy.put("GB", "Software \u2022 Applications");
		legacy.put("GC", "Software \u2022 Software Service & Support");
		legacy.put("H", "Learning Resources");
		legacy.put("HA", "Learning Resources \u2022 Reference Material");
		legacy.put("HB", "Learning Resources \u2022 Training Courses");
		legacy.put("I", "Movies");
		legacy.put("IA", "Movies \u2022 Movies & Videos");
		legacy.put("J", "Video");
		legacy.put("JA", "Video \u2022 Televisions & Flat Panels");
		legacy.put("JB", "Video \u2022 VCRs");
		legacy.put("JC", "Video \u2022 Blu-ray & DVD Players");
		legacy.put("JD", "Video \u2022 Camcorders & Digital Cameras");
		legacy.put("JE", "Video \u2022 Web TV");
		legacy.put("JF", "Video \u2022 Video Game Consoles");
		legacy.put("JG", "Video \u2022 Satellite TV");
		legacy.put("JH", "Video \u2022 DVRs");
		legacy.put("JI", "Video \u2022 Combined AV Devices");
		legacy.put("JJ", "Video \u2022 Car Audio / Video");
		legacy.put("JK", "Video \u2022 Digital AV Players & Recorders");
		legacy.put("K", "Audio");
		legacy.put("KA", "Audio \u2022 Home Audio");
		legacy.put("KB", "Audio \u2022 Portable Audio");
		legacy.put("KC", "Audio \u2022 Car Audio");
		legacy.put("KD", "Audio \u2022 Speakers");
		legacy.put("KE", "Audio \u2022 Headsets & Microphones");
		legacy.put("L", "Cameras & Optical Systems");
		legacy.put("LA", "Cameras & Optical Systems \u2022 Cameras");
		legacy.put("LB", "Cameras & Optical Systems \u2022 Lenses");
		legacy.put("LC", "Cameras & Optical Systems \u2022 Flashes");
		legacy.put("LD", "Cameras & Optical Systems \u2022 Binoculars");
		legacy.put("LE", "Cameras & Optical Systems \u2022 Telescopes");
		legacy.put("LF", "Cameras & Optical Systems \u2022 Filters");
		legacy.put("LG", "Cameras & Optical Systems \u2022 Film");
		legacy.put("LH", "Cameras & Optical Systems \u2022 Microscopes");
		legacy.put("M", "CE Options");
		legacy.put("MA", "CE Options \u2022 Antennas");
		legacy.put("MB", "CE Options \u2022 Tripods & Video Support Equipment");
		legacy.put("MC", "CE Options \u2022 AV Blank Media");
		legacy.put("MD", "CE Options \u2022 AV Furniture");
		legacy.put("ME", "CE Options \u2022 Carrying Cases");
		legacy.put("MF", "CE Options \u2022 Remote Controls");
		legacy.put("MG", "CE Options \u2022 Power Devices & Batteries");
		legacy.put("MH", "CE Options \u2022 Cables");
		legacy.put("MI", "CE Options \u2022 Accessories");
		legacy.put("MJ", "CE Options \u2022 Service & Support");
		legacy.put("MK", "CE Options \u2022 Photo & Video Accessories");
		legacy.put("MM", "CE Options \u2022 Gift & Prepaid Cards");
		legacy.put("N", "Specialized Electronics");
		legacy.put("NA", "Specialized Electronics \u2022 Radar Detectors");
		legacy.put("NB", "Specialized Electronics \u2022 Car Security Systems");
		legacy.put("O", "Office Machines");
		legacy.put("OA", "Office Machines \u2022 Multifunction & Office Machines");
		legacy.put("OB", "Office Machines \u2022 Office Shredders");
		legacy.put("OC", "Office Machines \u2022 Binding Machines");
		legacy.put("OD", "Office Machines \u2022 Typewriters");
		legacy.put("OE", "Office Machines \u2022 Calculators");
		legacy.put("OF", "Office Machines \u2022 Cash Registers");
		legacy.put("OG", "Office Machines \u2022 Time & Attendance Control");
		legacy.put("P", "Communication");
		legacy.put("PA", "Communication \u2022 Telephones");
		legacy.put("PB", "Communication \u2022 Mobile Phones");
		legacy.put("PC", "Communication \u2022 Pagers");
		legacy.put("PD", "Communication \u2022 Answering Machines & Caller ID");
		legacy.put("PE", "Communication \u2022 Two-Way Radios");
		legacy.put("PF", "Communication \u2022 GPS Receivers");
		legacy.put("PG", "Communication \u2022 GPS Kits");
		legacy.put("PH", "Communication \u2022 GPS Software");
		legacy.put("PI", "Communication \u2022 Marine Electronics");
		legacy.put("PJ", "Communication \u2022 Wearable Electronics");
		legacy.put("Q", "Automotive");
		legacy.put("QA", "Automotive \u2022 White Goods");
		legacy.put("QJ", "Automotive \u2022 Automotive Accessories");
		legacy.put("R", "Large Appliances");
		legacy.put("RA", "Large Appliances \u2022 Refrigerators & Freezers");
		legacy.put("RB", "Large Appliances \u2022 Ranges & Ovens");
		legacy.put("RC", "Large Appliances \u2022 Cooktops");
		legacy.put("RD", "Large Appliances \u2022 Hoods");
		legacy.put("RE", "Large Appliances \u2022 Dishwashers");
		legacy.put("RF", "Large Appliances \u2022 Microwave Ovens");
		legacy.put("RG", "Large Appliances \u2022 Large Appliance Accessories");
		legacy.put("RH", "Large Appliances \u2022 Washers & Dryers");
		legacy.put("S", "Small Appliances");
		legacy.put("SA", "Small Appliances \u2022 Vacuum Cleaners");
		legacy.put("SB", "Small Appliances \u2022 Food Processors");
		legacy.put("SC", "Small Appliances \u2022 Coffee Makers");
		legacy.put("SD", "Small Appliances \u2022 Irons");
		legacy.put("SE", "Small Appliances \u2022 Toasters & Grills");
		legacy.put("SF", "Small Appliances \u2022 Personal Care");
		legacy.put("SG", "Small Appliances \u2022 Heaters & Coolers");
		legacy.put("SH", "Small Appliances \u2022 Small Kitchen Appliances");
		legacy.put("SI", "Small Appliances \u2022 Small Appliances Accessories");
		legacy.put("SJ", "Small Appliances \u2022 Tableware");
		legacy.put("SK", "Small Appliances \u2022 Cutlery & Utensils");
		legacy.put("SL", "Small Appliances \u2022 Food Storage");
		legacy.put("SM", "Small Appliances \u2022 Cookware & Bakeware");
		legacy.put("SN", "Small Appliances \u2022 Weather Instruments");
		legacy.put("SO", "Small Appliances \u2022 Sewing Machines");
		legacy.put("T", "Studio Equipment");
		legacy.put("TA", "Studio Equipment \u2022 Backgrounds");
		legacy.put("TB", "Studio Equipment \u2022 Lighting Filters");
		legacy.put("TC", "Studio Equipment \u2022 Light Control");
		legacy.put("TD", "Studio Equipment \u2022 Studio Light & Flashes");
		legacy.put("TE", "Studio Equipment \u2022 Studio Mounting");
		legacy.put("TG", "Studio Equipment \u2022 Light Meters");
		legacy.put("U", "Darkroom");
		legacy.put("UA", "Darkroom \u2022 Photo Enlarging Paper");
		legacy.put("UB", "Darkroom \u2022 Photographic Chemistry");
		legacy.put("UD", "Darkroom \u2022 Enlargers & Components");
		legacy.put("UE", "Darkroom \u2022 Developing & Processing Equipment");
		legacy.put("UF", "Darkroom \u2022 Darkroom Accessories, Safelight & Setup");
		legacy.put("V", "Photo Storage & Presentation");
		legacy.put("VA", "Photo Storage & Presentation \u2022 Photo Frames");
		legacy.put("VB", "Photo Storage & Presentation \u2022 Photo Albums & Archival Storage");
		legacy.put("VC", "Photo Storage & Presentation \u2022 Cutters & Trimmers");
		legacy.put("VD", "Photo Storage & Presentation \u2022 Laminators");
		legacy.put("W", "Professional Video");
		legacy.put("WA", "Professional Video \u2022 Video Editing Controllers, Mixers & Titlers");
		legacy.put("WB", "Professional Video \u2022 Studio & Field Monitors");
		legacy.put("WC", "Professional Video \u2022 Studio & Production Equipment");
		legacy.put("X", "Professional Audio");
		legacy.put("XA", "Professional Audio \u2022 Audio Mixers");
		legacy.put("Y", "Area Security Systems");
		legacy.put("YA", "Area Security Systems \u2022 Time Lapse VCRs & DVRs");
		legacy.put("YB", "Area Security Systems \u2022 Quad Processors & Video Multiplexers");
		legacy.put("YC", "Area Security Systems \u2022 Video Surveillance Kits & Solutions");
		legacy.put("Z", "Musical Instruments");
		legacy.put("ZA", "Musical Instruments \u2022 String Instruments");
		legacy.put("ZB", "Musical Instruments \u2022 Wind Instruments");
		legacy.put("ZC", "Musical Instruments \u2022 Keyboard Instruments");
		legacy.put("ZD", "Musical Instruments \u2022 Percussion Instruments");
		legacy.put("ZE", "Musical Instruments \u2022 Amplifiers & Effects");
		legacy.put("ZF", "Musical Instruments \u2022 Lighting Equipment");
		legacy.put("ZG", "Musical Instruments \u2022 Musical Instrument Accessories");

	}
}
