package ua.pp.hak.util;

import java.util.HashMap;

public class Legacy {
	private static HashMap<String, String> legacy;

	static {
		initLegacy();
	}

	public static String getLecagyName(String legacyCode) {
		return legacy.get(legacyCode);
	}

	private static void initLegacy() {
		legacy = new HashMap<>();
		legacy.put("0", "Office Supplies");
		legacy.put("0A", "Office Supplies • Books & Pads");
		legacy.put("0B", "Office Supplies • Forms");
		legacy.put("0C", "Office Supplies • Writing & Drawing Tools");
		legacy.put("0D", "Office Supplies • Craft & Art Supplies");
		legacy.put("0E", "Office Supplies • Filing & Storage");
		legacy.put("0F", "Office Supplies • Presentation");
		legacy.put("0G", "Office Supplies • Presentation Accessories");
		legacy.put("0H", "Office Supplies • Clips, Pins & Staples");
		legacy.put("0I", "Office Supplies • Stamps & Accessories");
		legacy.put("0J", "Office Supplies • Desk Accessories");
		legacy.put("1", "Shipping & Packaging");
		legacy.put("1A", "Shipping & Packaging • Envelopes & Shipping Boxes");
		legacy.put("1B", "Shipping & Packaging • Tape & Dispensers");
		legacy.put("1C", "Shipping & Packaging • Packaging Materials");
		legacy.put("1D", "Shipping & Packaging • Mailroom & Packaging Equipment");
		legacy.put("2", "Janitorial & Facilities");
		legacy.put("2A", "Janitorial & Facilities • Trash Bags & Cans");
		legacy.put("2B", "Janitorial & Facilities • Cleaning Tools");
		legacy.put("2C", "Janitorial & Facilities • Household Chemicals");
		legacy.put("2D", "Janitorial & Facilities • Hygiene");
		legacy.put("2E", "Janitorial & Facilities • Lighting");
		legacy.put("2I", "Janitorial & Facilities • Workwear & Safety");
		legacy.put("2J", "Janitorial & Facilities • Signage & Posters");
		legacy.put("3", "Food & Beverages");
		legacy.put("3A", "Food & Beverages • Food");
		legacy.put("3B", "Food & Beverages • Beverages");
		legacy.put("3Z", "Food & Beverages • Quantity Units of Measure");
		legacy.put("4", "Furniture");
		legacy.put("4A", "Furniture • Surfaces");
		legacy.put("4B", "Furniture • Seating");
		legacy.put("4C", "Furniture • Storage Furniture");
		legacy.put("4D", "Furniture • Decoration");
		legacy.put("4K", "Furniture • Furniture Accessories");
		legacy.put("5", "Construction & Repair");
		legacy.put("5A", "Construction & Repair • Hand Tools");
		legacy.put("5B", "Construction & Repair • Power Tools");
		legacy.put("5C", "Construction & Repair • Construction Equipment");
		legacy.put("5D", "Construction & Repair • Locking Systems");
		legacy.put("5E", "Construction & Repair • Integrated Systems & Automation");
		legacy.put("5F", "Construction & Repair • Outdoor Power Tools");
		legacy.put("5G", "Construction & Repair • Power Tool Accessories");
		legacy.put("6", "Toys, Kids & Baby");
		legacy.put("6A", "Toys, Kids & Baby • Toys");
		legacy.put("6B", "Toys, Kids & Baby • Blocks & Building Sets");
		legacy.put("6C", "Toys, Kids & Baby • Games & Puzzles");
		legacy.put("6D", "Toys, Kids & Baby • Outdoor Play");
		legacy.put("7", "Sports & Recreation");
		legacy.put("7A", "Sports & Recreation • Exercise & Fitness Equipment");
		legacy.put("7B", "Sports & Recreation • Field, Court & Rink Equipment");
		legacy.put("7C", "Sports & Recreation • Cycling");
		legacy.put("7D", "Sports & Recreation • Scooters, Skateboards & Skates");
		legacy.put("7E", "Sports & Recreation • Leisure Sports & Game Room");
		legacy.put("9", "Clothing, Shoes & Jewelry");
		legacy.put("9C", "Clothing, Shoes & Jewelry • Watches");
		legacy.put("A", "Systems");
		legacy.put("AA", "Systems • Desktops & Servers");
		legacy.put("AB", "Systems • Notebooks");
		legacy.put("AC", "Systems • Tablets & e-Book Readers");
		legacy.put("AD", "Systems • Processor Upgrades");
		legacy.put("AE", "Systems • Motherboards");
		legacy.put("AF", "Systems • System Cabinets");
		legacy.put("AG", "Systems • UPS & Power Devices");
		legacy.put("AH", "Systems • System & Power Cables");
		legacy.put("AI", "Systems • Port Expansion");
		legacy.put("AJ", "Systems • System Accessories");
		legacy.put("AK", "Systems • System Service & Support");
		legacy.put("B", "Memory");
		legacy.put("BA", "Memory • RAM");
		legacy.put("BB", "Memory • Video Memory");
		legacy.put("BC", "Memory • Cache Memory");
		legacy.put("BD", "Memory • Flash Memory");
		legacy.put("BE", "Memory • Read-Only Memory");
		legacy.put("BF", "Memory • Memory Adapters");
		legacy.put("C", "Storage Devices");
		legacy.put("CA", "Storage Devices • Hard Drives");
		legacy.put("CB", "Storage Devices • Undefined");
		legacy.put("CC", "Storage Devices • Disk Drives");
		legacy.put("CD", "Storage Devices • Tape Drives");
		legacy.put("CE", "Storage Devices • Network Storage");
		legacy.put("CF", "Storage Devices • Removable Media");
		legacy.put("CG", "Storage Devices • Storage Adapters");
		legacy.put("CH", "Storage Devices • Storage Cables");
		legacy.put("CI", "Storage Devices • Storage Enclosures & RAID Arrays");
		legacy.put("CJ", "Storage Devices • Storage Accessories");
		legacy.put("CK", "Storage Devices • Storage Service & Support");
		legacy.put("D", "Input Devices");
		legacy.put("DA", "Input Devices • Keyboards");
		legacy.put("DB", "Input Devices • Pointing Devices");
		legacy.put("DC", "Input Devices • Game Controllers");
		legacy.put("DD", "Input Devices • Scanners");
		legacy.put("DE", "Input Devices • Bar Code Readers");
		legacy.put("DF", "Input Devices • Audio Input");
		legacy.put("DG", "Input Devices • PC & Network Cameras");
		legacy.put("DH", "Input Devices • Input Adapters");
		legacy.put("DI", "Input Devices • Input Cables");
		legacy.put("DJ", "Input Devices • Input Accessories");
		legacy.put("DK", "Input Devices • Input Service & Support");
		legacy.put("E", "Output Devices");
		legacy.put("EA", "Output Devices • Monitors");
		legacy.put("EB", "Output Devices • Presentation Monitors");
		legacy.put("EC", "Output Devices • Projectors");
		legacy.put("ED", "Output Devices • Printers");
		legacy.put("EE", "Output Devices • Audio Output");
		legacy.put("EF", "Output Devices • Video Cards");
		legacy.put("EG", "Output Devices • Sound Cards");
		legacy.put("EH", "Output Devices • Output Cables");
		legacy.put("EI", "Output Devices • Printer Consumables");
		legacy.put("EJ", "Output Devices • Output Accessories");
		legacy.put("EK", "Output Devices • Output Service & Support");
		legacy.put("F", "Networking");
		legacy.put("FA", "Networking • Modems");
		legacy.put("FB", "Networking • Video Conferencing");
		legacy.put("FC", "Networking • Concentrators & Multiplexers");
		legacy.put("FD", "Networking • Repeaters & Transceivers");
		legacy.put("FE", "Networking • Hubs & Switches");
		legacy.put("FF", "Networking • Bridges & Routers");
		legacy.put("FG", "Networking • Network Devices");
		legacy.put("FH", "Networking • Network Adapters");
		legacy.put("FI", "Networking • Network Cables");
		legacy.put("FJ", "Networking • Network Accessories");
		legacy.put("FK", "Networking • Network Service & Support");
		legacy.put("FL", "Networking • Network Testers");
		legacy.put("FM", "Networking • Business Phone Systems");
		legacy.put("G", "Software");
		legacy.put("GA", "Software • Operating Systems");
		legacy.put("GB", "Software • Applications");
		legacy.put("GC", "Software • Software Service & Support");
		legacy.put("H", "Learning Resources");
		legacy.put("HA", "Learning Resources • Reference Material");
		legacy.put("HB", "Learning Resources • Training Courses");
		legacy.put("I", "Movies");
		legacy.put("IA", "Movies • Movies & Videos");
		legacy.put("J", "Video");
		legacy.put("JA", "Video • Televisions & Flat Panels");
		legacy.put("JB", "Video • VCRs");
		legacy.put("JC", "Video • Blu-ray & DVD Players");
		legacy.put("JD", "Video • Camcorders & Digital Cameras");
		legacy.put("JE", "Video • Web TV");
		legacy.put("JF", "Video • Video Game Consoles");
		legacy.put("JG", "Video • Satellite TV");
		legacy.put("JH", "Video • DVRs");
		legacy.put("JI", "Video • Combined AV Devices");
		legacy.put("JJ", "Video • Car Audio / Video");
		legacy.put("JK", "Video • Digital AV Players & Recorders");
		legacy.put("K", "Audio");
		legacy.put("KA", "Audio • Home Audio");
		legacy.put("KB", "Audio • Portable Audio");
		legacy.put("KC", "Audio • Car Audio");
		legacy.put("KD", "Audio • Speakers");
		legacy.put("KE", "Audio • Headsets & Microphones");
		legacy.put("L", "Cameras & Optical Systems");
		legacy.put("LA", "Cameras & Optical Systems • Cameras");
		legacy.put("LB", "Cameras & Optical Systems • Lenses");
		legacy.put("LC", "Cameras & Optical Systems • Flashes");
		legacy.put("LD", "Cameras & Optical Systems • Binoculars");
		legacy.put("LE", "Cameras & Optical Systems • Telescopes");
		legacy.put("LF", "Cameras & Optical Systems • Filters");
		legacy.put("LG", "Cameras & Optical Systems • Film");
		legacy.put("LH", "Cameras & Optical Systems • Microscopes");
		legacy.put("M", "CE Options");
		legacy.put("MA", "CE Options • Antennas");
		legacy.put("MB", "CE Options • Tripods & Video Support Equipment");
		legacy.put("MC", "CE Options • AV Blank Media");
		legacy.put("MD", "CE Options • AV Furniture");
		legacy.put("ME", "CE Options • Carrying Cases");
		legacy.put("MF", "CE Options • Remote Controls");
		legacy.put("MG", "CE Options • Power Devices & Batteries");
		legacy.put("MH", "CE Options • Cables");
		legacy.put("MI", "CE Options • Accessories");
		legacy.put("MJ", "CE Options • Service & Support");
		legacy.put("MK", "CE Options • Photo & Video Accessories");
		legacy.put("MM", "CE Options • Gift & Prepaid Cards");
		legacy.put("N", "Specialized Electronics");
		legacy.put("NA", "Specialized Electronics • Radar Detectors");
		legacy.put("NB", "Specialized Electronics • Car Security Systems");
		legacy.put("O", "Office Machines");
		legacy.put("OA", "Office Machines • Multifunction & Office Machines");
		legacy.put("OB", "Office Machines • Office Shredders");
		legacy.put("OC", "Office Machines • Binding Machines");
		legacy.put("OD", "Office Machines • Typewriters");
		legacy.put("OE", "Office Machines • Calculators");
		legacy.put("OF", "Office Machines • Cash Registers");
		legacy.put("OG", "Office Machines • Time & Attendance Control");
		legacy.put("P", "Communication");
		legacy.put("PA", "Communication • Telephones");
		legacy.put("PB", "Communication • Mobile Phones");
		legacy.put("PC", "Communication • Pagers");
		legacy.put("PD", "Communication • Answering Machines & Caller ID");
		legacy.put("PE", "Communication • Two-Way Radios");
		legacy.put("PF", "Communication • GPS Receivers");
		legacy.put("PG", "Communication • GPS Kits");
		legacy.put("PH", "Communication • GPS Software");
		legacy.put("PI", "Communication • Marine Electronics");
		legacy.put("PJ", "Communication • Wearable Electronics");
		legacy.put("Q", "Automotive");
		legacy.put("QA", "Automotive • White Goods");
		legacy.put("QJ", "Automotive • Automotive Accessories");
		legacy.put("R", "Large Appliances");
		legacy.put("RA", "Large Appliances • Refrigerators & Freezers");
		legacy.put("RB", "Large Appliances • Ranges & Ovens");
		legacy.put("RC", "Large Appliances • Cooktops");
		legacy.put("RD", "Large Appliances • Hoods");
		legacy.put("RE", "Large Appliances • Dishwashers");
		legacy.put("RF", "Large Appliances • Microwave Ovens");
		legacy.put("RG", "Large Appliances • Large Appliance Accessories");
		legacy.put("RH", "Large Appliances • Washers & Dryers");
		legacy.put("S", "Small Appliances");
		legacy.put("SA", "Small Appliances • Vacuum Cleaners");
		legacy.put("SB", "Small Appliances • Food Processors");
		legacy.put("SC", "Small Appliances • Coffee Makers");
		legacy.put("SD", "Small Appliances • Irons");
		legacy.put("SE", "Small Appliances • Toasters & Grills");
		legacy.put("SF", "Small Appliances • Personal Care");
		legacy.put("SG", "Small Appliances • Heaters & Coolers");
		legacy.put("SH", "Small Appliances • Small Kitchen Appliances");
		legacy.put("SI", "Small Appliances • Small Appliances Accessories");
		legacy.put("SJ", "Small Appliances • Tableware");
		legacy.put("SK", "Small Appliances • Cutlery & Utensils");
		legacy.put("SL", "Small Appliances • Food Storage");
		legacy.put("SM", "Small Appliances • Cookware & Bakeware");
		legacy.put("SN", "Small Appliances • Weather Instruments");
		legacy.put("SO", "Small Appliances • Sewing Machines");
		legacy.put("T", "Studio Equipment");
		legacy.put("TA", "Studio Equipment • Backgrounds");
		legacy.put("TB", "Studio Equipment • Lighting Filters");
		legacy.put("TC", "Studio Equipment • Light Control");
		legacy.put("TD", "Studio Equipment • Studio Light & Flashes");
		legacy.put("TE", "Studio Equipment • Studio Mounting");
		legacy.put("TG", "Studio Equipment • Light Meters");
		legacy.put("U", "Darkroom");
		legacy.put("UA", "Darkroom • Photo Enlarging Paper");
		legacy.put("UB", "Darkroom • Photographic Chemistry");
		legacy.put("UD", "Darkroom • Enlargers & Components");
		legacy.put("UE", "Darkroom • Developing & Processing Equipment");
		legacy.put("UF", "Darkroom • Darkroom Accessories, Safelight & Setup");
		legacy.put("V", "Photo Storage & Presentation");
		legacy.put("VA", "Photo Storage & Presentation • Photo Frames");
		legacy.put("VB", "Photo Storage & Presentation • Photo Albums & Archival Storage");
		legacy.put("VC", "Photo Storage & Presentation • Cutters & Trimmers");
		legacy.put("VD", "Photo Storage & Presentation • Laminators");
		legacy.put("W", "Professional Video");
		legacy.put("WA", "Professional Video • Video Editing Controllers, Mixers & Titlers");
		legacy.put("WB", "Professional Video • Studio & Field Monitors");
		legacy.put("WC", "Professional Video • Studio & Production Equipment");
		legacy.put("X", "Professional Audio");
		legacy.put("XA", "Professional Audio • Audio Mixers");
		legacy.put("Y", "Area Security Systems");
		legacy.put("YA", "Area Security Systems • Time Lapse VCRs & DVRs");
		legacy.put("YB", "Area Security Systems • Quad Processors & Video Multiplexers");
		legacy.put("YC", "Area Security Systems • Video Surveillance Kits & Solutions");
		legacy.put("Z", "Musical Instruments");
		legacy.put("ZA", "Musical Instruments • String Instruments");
		legacy.put("ZB", "Musical Instruments • Wind Instruments");
		legacy.put("ZC", "Musical Instruments • Keyboard Instruments");
		legacy.put("ZD", "Musical Instruments • Percussion Instruments");
		legacy.put("ZE", "Musical Instruments • Amplifiers & Effects");
		legacy.put("ZF", "Musical Instruments • Lighting Equipment");
		legacy.put("ZG", "Musical Instruments • Musical Instrument Accessories");

	}
}
